import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "./globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Matheus Augusto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme className={`${rubik.variable} antialiased bg-background text-secondary`}>
          {children}
        </Theme>
      </body>
    </html>
  );
}
